#! /bin/bash

git-fuzzy-diff() {
    git rev-parse HEAD >/dev/null 2>&1 || return

    git diff "$@" --name-only | fzf -m --ansi --preview "git diff $* --color=always -- {-1}"
}

# from https://polothy.github.io/post/2019-08-19-fzf-git-checkout/
git-fuzzy-branch() {
    git rev-parse HEAD >/dev/null 2>&1 || return

    # shellcheck disable=SC2016
    git branch --color=always --all --sort=-committerdate |
        grep -v HEAD |
        sort --reverse |
        fzf --height 50% --ansi --no-multi --preview-window right:65% \
            --preview 'git log -n 50 --color=always --date=short --pretty=format:"%C(dim blue)[%ad]%C(reset) %C(bold normal)[%h]%C(reset) | %C(blue)%s %C(bold normal)[%an]%C(reset)%C(bold white)%d%C(reset)" --graph --date=short $(sed "s/.* //" <<< {})' |
        sed "s/.* //"
}

# from https://polothy.github.io/post/2019-08-19-fzf-git-checkout/
git-fuzzy-checkout() {
    git rev-parse HEAD >/dev/null 2>&1 || return

    local branch

    branch=$(git-fuzzy-branch)
    if [[ "$branch" = "" ]]; then
        echo "No branch selected."
        return
    fi

    # If branch name starts with 'remotes/' then it is a remote branch. By
    # using --track and a remote branch name, it is the same as:
    # git checkout -b branchName --track origin/branchName
    if [[ "$branch" = 'remotes/'* ]]; then
        git checkout --track "$branch"
    else
        git checkout "$branch"
    fi
}

git-fuzzy-rebase() {
    git rebase "$(git-fuzzy-branch)"
}

git-fuzzy-checkout-ticket() {
    ticket=$(jira issue list --no-headers --plain --columns KEY,SUMMARY -a "$(jira me)" -s "In Progress" | fzf)
    [[ -n $ticket ]] || exit 1
    ticket_id=$(echo "${ticket}" | choose 0)
    ticket_description=$(echo "${ticket}" | choose 1:)
    read -r -p "Define slug for [${ticket_description}]: " slug
    [ -z "${slug}" ] && slug="${ticket_description}"
    slug="${slug// /-}"
    git cob feature/"${ticket_id}"_"${slug}"
    git p
}

git-gitlab-code-review() {
    git fetch origin refs/merge-requests/"${0}"/head
    git switch --detach FETCH_HEAD
    git reset "$(git merge-base HEAD "$(git remote show origin | grep HEAD | sed 's/.* //')")"
}
