[tools]
awscli = ["latest"]
bun = ["latest"]
deno = ["latest"]
java = ["latest"]
node = ["latest"]
pnpm = ["latest"]
python = ["latest"]
rust = ["latest"]
terraform = ["latest"]
uv = ["latest"]
yarn = ["latest"]

[settings]
idiomatic_version_file_enable_tools = ["node"]
