[tools]
aws-cli = ["latest"]
aws-cdk = ["2.1135"]
bun = ["latest"]
deno = ["latest"]
herdr = ["latest"]
hunk = ["latest"]
java = ["latest"]
node = ["latest"]
pnpm = ["latest"]
python = ["latest"]
rust = ["latest"]
terraform = ["latest"]
uv = ["latest"]
yarn = ["latest"]

[settings]
idiomatic_version_file_enable_tools = ["node"]
