#!/bin/sh

# from https://medium.com/@joaomoreno/persistent-terminal-sessions-in-vs-code-8fc469ed6b41
SESSION="idea-$(pwd)"
/usr/local/opt/tmux/bin/tmux attach-session -d -t "$SESSION" || /usr/local/opt/tmux/bin/tmux new-session -s "$SESSION"
