#!/bin/sh

# from https://medium.com/@joaomoreno/persistent-terminal-sessions-in-vs-code-8fc469ed6b41
if [ "$(arch)" = "arm64" ]; then
     eval "$(/opt/homebrew/bin/brew shellenv)"
 else
     eval "$(/usr/local/bin/brew shellenv)"
 fi
SESSION=$(echo "idea-$(pwd)" | sed 's/\./_/g')
tmux attach-session -d -t "$SESSION" || tmux new-session -s "$SESSION"
