---
name: Lint
on: push

jobs:
  linter:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # vscode json settings comments break linting
          VALIDATE_JSON: false
