---
name: Lint
on: push

jobs:
  linter:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Lint Code Base
        uses: docker://github/super-linter:v5
        env:
          # vscode json settings comments break linting
          VALIDATE_JSON: false
          FILTER_REGEX_EXCLUDE: 'nvim\/kickstart.nvim'
